# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\yestupin2\Desktop\CP_NewUI.ui'
#
# Created: Tue May 12 16:03:58 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(439, 282)
        Form.setMaximumSize(QtCore.QSize(800, 600))
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.sceneLayout = QtGui.QGridLayout()
        self.sceneLayout.setObjectName("sceneLayout")
        self.sceneGRP = QtGui.QGroupBox(Form)
        self.sceneGRP.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sceneGRP.setObjectName("sceneGRP")
        self.gridLayout_6 = QtGui.QGridLayout(self.sceneGRP)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.seqLBL = QtGui.QLabel(self.sceneGRP)
        self.seqLBL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.seqLBL.setObjectName("seqLBL")
        self.gridLayout_6.addWidget(self.seqLBL, 0, 0, 1, 1)
        self.sequenceBOX = QtGui.QComboBox(self.sceneGRP)
        self.sequenceBOX.setObjectName("sequenceBOX")
        self.sequenceBOX.addItem("")
        self.sequenceBOX.addItem("")
        self.sequenceBOX.addItem("")
        self.sequenceBOX.addItem("")
        self.sequenceBOX.addItem("")
        self.gridLayout_6.addWidget(self.sequenceBOX, 0, 1, 1, 1)
        self.shotLBL = QtGui.QLabel(self.sceneGRP)
        self.shotLBL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.shotLBL.setObjectName("shotLBL")
        self.gridLayout_6.addWidget(self.shotLBL, 0, 2, 1, 1)
        self.shotBOX = QtGui.QComboBox(self.sceneGRP)
        self.shotBOX.setObjectName("shotBOX")
        self.shotBOX.addItem("")
        self.shotBOX.addItem("")
        self.shotBOX.addItem("")
        self.shotBOX.addItem("")
        self.shotBOX.addItem("")
        self.shotBOX.addItem("")
        self.shotBOX.addItem("")
        self.shotBOX.addItem("")
        self.shotBOX.addItem("")
        self.shotBOX.addItem("")
        self.shotBOX.addItem("")
        self.shotBOX.addItem("")
        self.shotBOX.addItem("")
        self.shotBOX.addItem("")
        self.shotBOX.addItem("")
        self.shotBOX.addItem("")
        self.shotBOX.addItem("")
        self.shotBOX.addItem("")
        self.shotBOX.addItem("")
        self.shotBOX.addItem("")
        self.shotBOX.addItem("")
        self.shotBOX.addItem("")
        self.shotBOX.addItem("")
        self.shotBOX.addItem("")
        self.shotBOX.addItem("")
        self.shotBOX.addItem("")
        self.shotBOX.addItem("")
        self.shotBOX.addItem("")
        self.gridLayout_6.addWidget(self.shotBOX, 0, 3, 1, 1)
        self.sceneLayout.addWidget(self.sceneGRP, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.sceneLayout, 0, 0, 1, 1)
        self.characterLayout = QtGui.QVBoxLayout()
        self.characterLayout.setObjectName("characterLayout")
        self.characterGRP = QtGui.QGroupBox(Form)
        self.characterGRP.setObjectName("characterGRP")
        self.gridLayout_2 = QtGui.QGridLayout(self.characterGRP)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rockyCHK = QtGui.QCheckBox(self.characterGRP)
        self.rockyCHK.setObjectName("rockyCHK")
        self.gridLayout_2.addWidget(self.rockyCHK, 0, 0, 1, 1)
        self.raggedyCHK = QtGui.QCheckBox(self.characterGRP)
        self.raggedyCHK.setObjectName("raggedyCHK")
        self.gridLayout_2.addWidget(self.raggedyCHK, 0, 1, 1, 1)
        self.scrawnyCHK = QtGui.QCheckBox(self.characterGRP)
        self.scrawnyCHK.setObjectName("scrawnyCHK")
        self.gridLayout_2.addWidget(self.scrawnyCHK, 0, 2, 1, 1)
        self.longbeakCHK = QtGui.QCheckBox(self.characterGRP)
        self.longbeakCHK.setObjectName("longbeakCHK")
        self.gridLayout_2.addWidget(self.longbeakCHK, 0, 3, 1, 1)
        self.heavyCHK = QtGui.QCheckBox(self.characterGRP)
        self.heavyCHK.setObjectName("heavyCHK")
        self.gridLayout_2.addWidget(self.heavyCHK, 0, 4, 1, 1)
        self.boxyCHK = QtGui.QCheckBox(self.characterGRP)
        self.boxyCHK.setObjectName("boxyCHK")
        self.gridLayout_2.addWidget(self.boxyCHK, 0, 5, 1, 1)
        self.joeCHK = QtGui.QCheckBox(self.characterGRP)
        self.joeCHK.setObjectName("joeCHK")
        self.gridLayout_2.addWidget(self.joeCHK, 1, 0, 1, 1)
        self.ernestCHK = QtGui.QCheckBox(self.characterGRP)
        self.ernestCHK.setObjectName("ernestCHK")
        self.gridLayout_2.addWidget(self.ernestCHK, 1, 1, 1, 1)
        self.vincentCHK = QtGui.QCheckBox(self.characterGRP)
        self.vincentCHK.setObjectName("vincentCHK")
        self.gridLayout_2.addWidget(self.vincentCHK, 1, 2, 1, 1)
        self.georgeCHK = QtGui.QCheckBox(self.characterGRP)
        self.georgeCHK.setObjectName("georgeCHK")
        self.gridLayout_2.addWidget(self.georgeCHK, 1, 3, 1, 1)
        self.bobCHK = QtGui.QCheckBox(self.characterGRP)
        self.bobCHK.setObjectName("bobCHK")
        self.gridLayout_2.addWidget(self.bobCHK, 1, 4, 1, 1)
        self.tomCHK = QtGui.QCheckBox(self.characterGRP)
        self.tomCHK.setObjectName("tomCHK")
        self.gridLayout_2.addWidget(self.tomCHK, 1, 5, 1, 1)
        self.characterLayout.addWidget(self.characterGRP)
        self.gridLayout.addLayout(self.characterLayout, 1, 0, 1, 1)
        self.importLayout = QtGui.QGridLayout()
        self.importLayout.setObjectName("importLayout")
        self.importGRP = QtGui.QGroupBox(Form)
        self.importGRP.setObjectName("importGRP")
        self.gridLayout_7 = QtGui.QGridLayout(self.importGRP)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.envBTN = QtGui.QPushButton(self.importGRP)
        self.envBTN.setObjectName("envBTN")
        self.gridLayout_7.addWidget(self.envBTN, 0, 0, 1, 1)
        self.geoBTN = QtGui.QPushButton(self.importGRP)
        self.geoBTN.setEnabled(True)
        self.geoBTN.setFlat(False)
        self.geoBTN.setObjectName("geoBTN")
        self.gridLayout_7.addWidget(self.geoBTN, 0, 1, 1, 1)
        self.abcBTN = QtGui.QPushButton(self.importGRP)
        self.abcBTN.setEnabled(True)
        self.abcBTN.setObjectName("abcBTN")
        self.gridLayout_7.addWidget(self.abcBTN, 0, 2, 1, 1)
        self.camBTN = QtGui.QPushButton(self.importGRP)
        self.camBTN.setObjectName("camBTN")
        self.gridLayout_7.addWidget(self.camBTN, 0, 3, 1, 1)
        self.lightsBTN = QtGui.QPushButton(self.importGRP)
        self.lightsBTN.setObjectName("lightsBTN")
        self.gridLayout_7.addWidget(self.lightsBTN, 0, 4, 1, 1)
        self.importLayout.addWidget(self.importGRP, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.importLayout, 2, 0, 1, 1)
        self.toolLayout = QtGui.QGridLayout()
        self.toolLayout.setObjectName("toolLayout")
        self.toolGRP = QtGui.QGroupBox(Form)
        self.toolGRP.setObjectName("toolGRP")
        self.gridLayout_8 = QtGui.QGridLayout(self.toolGRP)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.createLayerBTN = QtGui.QPushButton(self.toolGRP)
        self.createLayerBTN.setObjectName("createLayerBTN")
        self.gridLayout_8.addWidget(self.createLayerBTN, 0, 0, 1, 1)
        self.frameRangeBTN = QtGui.QPushButton(self.toolGRP)
        self.frameRangeBTN.setObjectName("frameRangeBTN")
        self.gridLayout_8.addWidget(self.frameRangeBTN, 0, 1, 1, 1)
        self.shotgunBTN = QtGui.QPushButton(self.toolGRP)
        self.shotgunBTN.setObjectName("shotgunBTN")
        self.gridLayout_8.addWidget(self.shotgunBTN, 0, 2, 1, 1)
        self.renderBTN = QtGui.QPushButton(self.toolGRP)
        self.renderBTN.setObjectName("renderBTN")
        self.gridLayout_8.addWidget(self.renderBTN, 0, 3, 1, 1)
        self.toolLayout.addWidget(self.toolGRP, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.toolLayout, 3, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "CURPIGEON SETUP", None, QtGui.QApplication.UnicodeUTF8))
        self.sceneGRP.setTitle(QtGui.QApplication.translate("Form", "SCENE", None, QtGui.QApplication.UnicodeUTF8))
        self.seqLBL.setText(QtGui.QApplication.translate("Form", "SEQUENCE", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceBOX.setItemText(0, QtGui.QApplication.translate("Form", "01", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceBOX.setItemText(1, QtGui.QApplication.translate("Form", "02", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceBOX.setItemText(2, QtGui.QApplication.translate("Form", "03", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceBOX.setItemText(3, QtGui.QApplication.translate("Form", "04", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceBOX.setItemText(4, QtGui.QApplication.translate("Form", "05", None, QtGui.QApplication.UnicodeUTF8))
        self.shotLBL.setText(QtGui.QApplication.translate("Form", "SHOT", None, QtGui.QApplication.UnicodeUTF8))
        self.shotBOX.setItemText(0, QtGui.QApplication.translate("Form", "01", None, QtGui.QApplication.UnicodeUTF8))
        self.shotBOX.setItemText(1, QtGui.QApplication.translate("Form", "02", None, QtGui.QApplication.UnicodeUTF8))
        self.shotBOX.setItemText(2, QtGui.QApplication.translate("Form", "03", None, QtGui.QApplication.UnicodeUTF8))
        self.shotBOX.setItemText(3, QtGui.QApplication.translate("Form", "04", None, QtGui.QApplication.UnicodeUTF8))
        self.shotBOX.setItemText(4, QtGui.QApplication.translate("Form", "05", None, QtGui.QApplication.UnicodeUTF8))
        self.shotBOX.setItemText(5, QtGui.QApplication.translate("Form", "06", None, QtGui.QApplication.UnicodeUTF8))
        self.shotBOX.setItemText(6, QtGui.QApplication.translate("Form", "07", None, QtGui.QApplication.UnicodeUTF8))
        self.shotBOX.setItemText(7, QtGui.QApplication.translate("Form", "08", None, QtGui.QApplication.UnicodeUTF8))
        self.shotBOX.setItemText(8, QtGui.QApplication.translate("Form", "09", None, QtGui.QApplication.UnicodeUTF8))
        self.shotBOX.setItemText(9, QtGui.QApplication.translate("Form", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.shotBOX.setItemText(10, QtGui.QApplication.translate("Form", "11", None, QtGui.QApplication.UnicodeUTF8))
        self.shotBOX.setItemText(11, QtGui.QApplication.translate("Form", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.shotBOX.setItemText(12, QtGui.QApplication.translate("Form", "13", None, QtGui.QApplication.UnicodeUTF8))
        self.shotBOX.setItemText(13, QtGui.QApplication.translate("Form", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.shotBOX.setItemText(14, QtGui.QApplication.translate("Form", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.shotBOX.setItemText(15, QtGui.QApplication.translate("Form", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.shotBOX.setItemText(16, QtGui.QApplication.translate("Form", "17", None, QtGui.QApplication.UnicodeUTF8))
        self.shotBOX.setItemText(17, QtGui.QApplication.translate("Form", "18", None, QtGui.QApplication.UnicodeUTF8))
        self.shotBOX.setItemText(18, QtGui.QApplication.translate("Form", "19", None, QtGui.QApplication.UnicodeUTF8))
        self.shotBOX.setItemText(19, QtGui.QApplication.translate("Form", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.shotBOX.setItemText(20, QtGui.QApplication.translate("Form", "21", None, QtGui.QApplication.UnicodeUTF8))
        self.shotBOX.setItemText(21, QtGui.QApplication.translate("Form", "22", None, QtGui.QApplication.UnicodeUTF8))
        self.shotBOX.setItemText(22, QtGui.QApplication.translate("Form", "23", None, QtGui.QApplication.UnicodeUTF8))
        self.shotBOX.setItemText(23, QtGui.QApplication.translate("Form", "24", None, QtGui.QApplication.UnicodeUTF8))
        self.shotBOX.setItemText(24, QtGui.QApplication.translate("Form", "25", None, QtGui.QApplication.UnicodeUTF8))
        self.shotBOX.setItemText(25, QtGui.QApplication.translate("Form", "26", None, QtGui.QApplication.UnicodeUTF8))
        self.shotBOX.setItemText(26, QtGui.QApplication.translate("Form", "27", None, QtGui.QApplication.UnicodeUTF8))
        self.shotBOX.setItemText(27, QtGui.QApplication.translate("Form", "28", None, QtGui.QApplication.UnicodeUTF8))
        self.characterGRP.setTitle(QtGui.QApplication.translate("Form", "CHARACTERS", None, QtGui.QApplication.UnicodeUTF8))
        self.rockyCHK.setText(QtGui.QApplication.translate("Form", "Rocky", None, QtGui.QApplication.UnicodeUTF8))
        self.raggedyCHK.setText(QtGui.QApplication.translate("Form", "Raggedy", None, QtGui.QApplication.UnicodeUTF8))
        self.scrawnyCHK.setText(QtGui.QApplication.translate("Form", "Scrawny", None, QtGui.QApplication.UnicodeUTF8))
        self.longbeakCHK.setText(QtGui.QApplication.translate("Form", "Longbeak", None, QtGui.QApplication.UnicodeUTF8))
        self.heavyCHK.setText(QtGui.QApplication.translate("Form", "Heavy", None, QtGui.QApplication.UnicodeUTF8))
        self.boxyCHK.setText(QtGui.QApplication.translate("Form", "Boxy", None, QtGui.QApplication.UnicodeUTF8))
        self.joeCHK.setText(QtGui.QApplication.translate("Form", "Joe", None, QtGui.QApplication.UnicodeUTF8))
        self.ernestCHK.setText(QtGui.QApplication.translate("Form", "Ernest", None, QtGui.QApplication.UnicodeUTF8))
        self.vincentCHK.setText(QtGui.QApplication.translate("Form", "Vincent", None, QtGui.QApplication.UnicodeUTF8))
        self.georgeCHK.setText(QtGui.QApplication.translate("Form", "George", None, QtGui.QApplication.UnicodeUTF8))
        self.bobCHK.setText(QtGui.QApplication.translate("Form", "Bob", None, QtGui.QApplication.UnicodeUTF8))
        self.tomCHK.setText(QtGui.QApplication.translate("Form", "Tom", None, QtGui.QApplication.UnicodeUTF8))
        self.importGRP.setTitle(QtGui.QApplication.translate("Form", "IMPORT", None, QtGui.QApplication.UnicodeUTF8))
        self.envBTN.setText(QtGui.QApplication.translate("Form", "ENV", None, QtGui.QApplication.UnicodeUTF8))
        self.geoBTN.setText(QtGui.QApplication.translate("Form", "GEO", None, QtGui.QApplication.UnicodeUTF8))
        self.abcBTN.setText(QtGui.QApplication.translate("Form", "ABC", None, QtGui.QApplication.UnicodeUTF8))
        self.camBTN.setText(QtGui.QApplication.translate("Form", "CAM", None, QtGui.QApplication.UnicodeUTF8))
        self.lightsBTN.setText(QtGui.QApplication.translate("Form", "LIGHTS", None, QtGui.QApplication.UnicodeUTF8))
        self.toolGRP.setTitle(QtGui.QApplication.translate("Form", "TOOLS", None, QtGui.QApplication.UnicodeUTF8))
        self.createLayerBTN.setText(QtGui.QApplication.translate("Form", "CREATE LYR", None, QtGui.QApplication.UnicodeUTF8))
        self.frameRangeBTN.setText(QtGui.QApplication.translate("Form", "FRAME RANGE", None, QtGui.QApplication.UnicodeUTF8))
        self.shotgunBTN.setText(QtGui.QApplication.translate("Form", "SHOTGUN", None, QtGui.QApplication.UnicodeUTF8))
        self.renderBTN.setText(QtGui.QApplication.translate("Form", "SET RENDER", None, QtGui.QApplication.UnicodeUTF8))

